package com.example.stellar.enums

enum class ActivityTypes {
    MAIN_ACTIVITY,
    LOGIN_ACTIVITY,
    REGISTER_ACTIVITY,
    GROUP_ACTIVITY,
    CREATE_GROUP_ACTIVITY,
    CREATE_POST_ACTIVITY,
    NOTIFICATION_ACTIVITY,
    PROFILE_ACTIVITY,
    SEARCH_ACTIVITY
}